name: Continous Deployment
On:
  push :
    branches:

     -main
  workflows_dispatch:

jobs:
   CI:
     uses: ./.github/workflows/ci.yml


   steps:
     - uses: actions/checkout@v3

     - name: tag commit
       run: git tag 1.0.0_${{github.run_id}}

