name: Build

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main
 workflow_dispatch:
 workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read|write|none
      attestations: read|write|none
      checks: read|write|none
      contents: read|write|none
      deployments: read|write|none
      id-token: write|none
      issues: read|write|none
      discussions: read|write|none
      packages: read|write|none
      pages: read|write|none
      pull-requests: read|write|none
      repository-projects: read|write|none
      security-events: read|write|none
      statuses: read|write|none

    steps:
      - uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
          cache: maven

      - name: install maven
        uses: stCarolas/setup-maven@v5

      - name: Build
        run:  |
              mvn clean install