name: Build

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main
 workflow_dispatch:
 workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3