name: Build

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main
 workflow_dispatch:
 workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
          cache: maven

      - name: install maven
        uses: stCarolas/setup-maven@v5

      - name: Build
        run:  |
              mvn clean install